name: Python on Ubuntu

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '43 6 * * 1'

jobs:
  ubuntu_builtin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:24.04"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
            build-essential \
            libffi-dev \
            python3-full \
            python3-dev \
            python3-pip \
            python3-setuptools \
            automake \
            autoconf \
            libtool
      - name: Build
        run: |
          python3 -m venv $HOME/venv && \
          BUILD_LIB=1 $HOME/venv/bin/pip3 install .
      - name: Test
        run: |
          $HOME/venv/bin/pip3 install pytest && \
          $HOME/venv/bin/py.test

  ubuntu_system:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ["ubuntu:24.04"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
            build-essential \
            libffi-dev \
            python3-full \
            python3-dev \
            python3-pip \
            python3-setuptools \
            libfuzzy-dev \
            automake \
            autoconf \
            libtool
      - name: Build
        run: |
          python3 -m venv $HOME/venv && \
          BUILD_LIB=1 $HOME/venv/bin/pip3 install .
      - name: Test
        run: |
          $HOME/venv/bin/pip3 install pytest && \
          $HOME/venv/bin/py.test
